[[plugins]]
package = "@netlify/buildbot-plugin-cache"

[[plugins]]
package = "@netlify/plugin-cache"
  [plugins.inputs]
  path = "node_modules/.cache"

[[build]]
  command = "npm install -g @angular/cli && npm run build"
