version: "3.8"
services:
  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes:
      - ./backend:/var/www/html

  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
      - angular-app

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: benchmark-hospitalar-db
      POSTGRES_USER: atec
      POSTGRES_PASSWORD: atec
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
