services:
  laravel-app:
    image: hma/laravel:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile.laravel
    ports:
      - "8001:8001"
    environment:
      APP_ENV: local
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: bh_db
      DB_USERNAME: atec
      DB_PASSWORD: atec123
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db


  db:
    image: postgres:12
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: atec
      POSTGRES_PASSWORD: atec123
      POSTGRES_DB: bh_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    

  # angular-app:
  #   image: hma/angular:1.0.0
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.angular
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   user: "front"


  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./frontend/nginx.conf:/etc/nginx/nginx.conf
  #     - ./frontend/dist:/usr/share/nginx/html
  #   depends_on:
  #     - laravel-app
  #     - angular-app

volumes:
  postgres-data:
  node_modules:
    driver: local