version: "3.9"
services:
  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgresql
    volumes:
      - ./backend:/var/www/html

  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
      - angular-app
      
  postgresql:
    container_name: pgsql_container
    image: postgres
    restart: always
    volumes:
      - /home/julio/projects/atec-final-project/data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=atec
      - POSTGRES_DB=${POSTGRES_DATABASE:-benchmarking_hospitalar_db}
      - POSTGRES_USER=${POSTGRES_USER:-atec123}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
