services:
  laravel-app:
    image: hma/laravel:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile.laravel
    ports:
      - "8001:8001"
    environment:
      APP_ENV: local
      RESET_SEEDERS: true
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: bh_db
      DB_USERNAME: atec
      DB_PASSWORD: atec

    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: bh_db
      POSTGRES_USER: atec
      POSTGRES_PASSWORD: atec
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: