version: '3.8'

services:

  laravel-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  angular-app:
    build:
      context: .
      dockerfile: docker/angular/Dockerfile
      args:
        - ANGULAR_DIST=./frontend/dist/frontend/browser
    ports:
      - "4200:80"  # Mapeando a porta 4200 do host para a porta 80 do contêiner
    depends_on:
      - laravel-app

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - ANGULAR_DIST=./frontend/dist/frontend/browser
    ports:
      - "8000:80"  # Mapeando a porta 8000 do host para a porta 80 do contêiner
    volumes:
      - ./backend/public:/var/www/public
    depends_on:
      - laravel-app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: benchmarking_hospitalar
      POSTGRES_USER: atec
      POSTGRES_PASSWORD: atec123
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgsql_data: