version: "3.9"

services:
  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    depends_on:
      - postgresql
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - app-network

  postgresql:
    image: postgres
    container_name: pgsql_container
    restart: always
    volumes:
      - pgsql_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=atec
      - POSTGRES_DB=benchmarking_hospitalar_db
      - POSTGRES_USER=atec
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgsql_data: