name: Backend Continuous Integration

on:
  push:
    branches:
      - 'testado'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'back')
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo_pgsql
          tools: composer, phpunit
      - name: Change to Laravel project directory
        run: cd backend

      - name: Install Laravel dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./backend

      - name: Run Laravel tests

        run: |
          php artisan key:generate --env=testing
          php artisan test

        working-directory: ./backend
        
  create-pull-request:
    needs: test-backend
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'testado'
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"

          github_token: ${{ secrets.GH_TOKEN }}

          pr_title: "Automated PR to merge testado into main"
          pr_body: "This is an automated pull request to update the main branch with the latest code from testado."
          pr_label: "automerge"