name: Backend Continuous Integration

on:
  push:
    branches:
      - 'testado'
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'back')
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo_pgsql
          tools: composer, phpunit
      - name: Install Laravel dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./backend
      - name: Run Laravel tests
        run: |
          cp .env.example .env
          php artisan key:generate --env=testing
          php artisan migrate --env=testing
          php artisan test
        working-directory: ./backend

  create-pull-request:
    needs: test-backend
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GH_TOKEN }}
          pr_title: "Automated PR to merge testado into main"
          pr_body: "This is an automated pull request to update the main branch with the latest code from testado."
          pr_label: "automerge"

  deploy-to-render:
    needs: create-pull-request
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ env.SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ env.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": false}'