name: Frontend Continuous Integration

on:
  push:
    branches:
      - 'testado'

jobs:
  test-frontend:
    if: github.ref_type == 'branch' && (github.event.ref == 'refs/heads/devF1' || github.event.ref == 'refs/heads/devF2')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install Angular dependencies
      run: npm install
    - name: Run Angular tests
      run: ng test --watch=false --browsers=ChromeHeadless